title: Anuja Deshpande
logo: "AnujaImagePortfolio.JPEG?raw=true"
description: >
  Email: anuja0507@gmail.com 
  <br><br>
  Country: Melbourne, Australia 
  <br><br>
  Citizenship: Australian Citizen 
  <br><br>
  Education: 
  Bachelor of Engineering (B.E.) in Electronics & Telecommunication, 
  Yeshwantrao Chavan College of Engineering (Y.C.C.E.), Nagpur, India 
  July 2006 - June 2010
  <br><br>
  <a href="https://www.linkedin.com/in/anuja-deshpande-a271b45b/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0
