title: Anuja Deshpande
logo: "AnujaImagePortfolio.JPEG?raw=true"
description:
  Email: anuja0507@gmail.com
  Country: Melbourne, Australia 
  Citizenship: Australian Citizen 
  
# <a href="https://www.linkedin.com/in/anuja-deshpande-a271b45b/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0
